### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException: For input string: "–7"

### ISSUE THREAD

**Issue by IamRegina** [Newbilius/HabrStatisticCollector#1]
Дмитрий, добрый день!

Большое спасибо за HabrStatisticsCollector!
Не получилось загрузить статистику из-за статьи https://habr.com/ru/company/lawboot/blog/312498/.
У нее отрицательный рейтинг в отличие от остальных, вожможно в этом проблема.

Заранее благодарю!
Регина

**Comment by Newbilius** [comment]
Исправил в свежем релизе :-)
https://github.com/Newbilius/HabrStatisticCollector/releases/tag/1.3
